// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWsw-xjXupYXIDRiPEI0nVCUslC7cPC-o',
    appId: '1:806321831421:web:a9622feed27f5e04356d94',
    messagingSenderId: '806321831421',
    projectId: 'hackdol-flutter',
    authDomain: 'hackdol-flutter.firebaseapp.com',
    storageBucket: 'hackdol-flutter.appspot.com',
    measurementId: 'G-KD9G7E6QMB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMor2J9aNOCX9FJKeXta8sRoyIhkVWlO8',
    appId: '1:806321831421:android:2778f7241857671e356d94',
    messagingSenderId: '806321831421',
    projectId: 'hackdol-flutter',
    storageBucket: 'hackdol-flutter.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWsw-xjXupYXIDRiPEI0nVCUslC7cPC-o',
    appId: '1:806321831421:web:2e8cac4d3b02baa6356d94',
    messagingSenderId: '806321831421',
    projectId: 'hackdol-flutter',
    authDomain: 'hackdol-flutter.firebaseapp.com',
    storageBucket: 'hackdol-flutter.appspot.com',
    measurementId: 'G-2FB1NM1W20',
  );
}
